version: '3.9'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: graphql_compras
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
