# DevTools
spring:
  devtools:
    restart:
      additional-exclude: logs/**

# MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/graphql_compras?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: null
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        ddl-auto: none

# Logging
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    org.hibernate.SQL: debug
